### ISSUE TITLE
Corrupted .wav file

### ISSUE THREAD

**Issue by samiaShoukat2023** [purecloudlabs/audiohook-reference-implementation#4]
The generated wav file is corrupted, and is not being opened in the player. Please assist in this regard.
I have attached the corrupted file along with the console logs for your reference.
[SampleFiles.zip](https://github.com/purecloudlabs/audiohook-reference-implementation/files/12161585/SampleFiles.zip)

**Comment by camiel-genesys** [comment]
I see that you are requesting a single channel from the client.
Question:
- Are you using the client tool to make the call or is this call coming from Genesys?

Thanks,
Camiel

**Comment by samiaShoukat2023** [comment]
Using Client tool to stream sample WAV file (@ Mono 8000 Hz). Both client and Server are communicating on the local-loop/localhost IP

Input File: [InputFile.zip](https://github.com/purecloudlabs/audiohook-reference-implementation/files/12161868/InputFile.zip)

**Comment by camiel-genesys** [comment]
We recently fixed an issue related to the PCMU header: https://github.com/purecloudlabs/audiohook-reference-implementation/pull/3

Could you please try again with the latest version?

Thanks,
Camiel

**Comment by samiaShoukat2023** [comment]
Thanks for the update @camiel-genesys 
Let me check and get back to you.

**Comment by samiaShoukat2023** [comment]
Thanks @camiel-genesys for your support.
It is working fine now.

**Comment by karancode-singh** [comment]
> Thanks @camiel-genesys for your support.
> It is working fine now.

Closing the issue
